import os
import time
import csv
import gc
import cv2
import numpy as np
import open3d as o3d

from colmap_loader import load_colmap_model
from mesh_generator import generate_mesh

print("[RECONSTRUCTION] COLMAP result processing module loaded")


# =========================================================
# LOAD IMAGE
# =========================================================

def process_single_image(image_info):
    """
    image_info must contain:
        {
            "path": "...",
            "name": "image_001.JPG"
        }

    IMPORTANT:
    Do NOT rotate images here.
    COLMAP poses/intrinsics correspond to the original image orientation.
    """

    path = image_info["path"]
    name = image_info["name"]

# Read image
    img = cv2.imread(
        path,
        cv2.IMREAD_COLOR
    )

    if img is None:
        print(f"[WARNING] Failed to load image: {path}")
        return None

    # -------------------------------------------------
    # MEMORY OPTIMIZATION
    # -------------------------------------------------
    # Large DSLR/mobile images consume huge amounts
    # of RAM. Downscale them before any processing.
    # COLMAP has already estimated the poses, so
    # moderate resizing will not affect pose loading.
    # -------------------------------------------------

    MAX_IMAGE_WIDTH = 2000

    h, w = img.shape[:2]

    if w > MAX_IMAGE_WIDTH:

        scale = MAX_IMAGE_WIDTH / float(w)

        new_w = int(w * scale)
        new_h = int(h * scale)

        img = cv2.resize(
            img,
            (new_w, new_h),
            interpolation=cv2.INTER_AREA
        )

    print(
        f"[IMAGE] {name}: "
        f"{w}x{h}  -->  "
        f"{img.shape[1]}x{img.shape[0]}"
    )

    return {
        "image": img,
        "name": name,
        "path": path
    }


# =========================================================
# SAVE POINT CLOUD
# =========================================================

def save_point_cloud(points, colors, output_path):

    os.makedirs(
        os.path.dirname(output_path),
        exist_ok=True
    )

    pcd = o3d.geometry.PointCloud()

    pcd.points = o3d.utility.Vector3dVector(
        np.asarray(points, dtype=np.float64)
    )

    pcd.colors = o3d.utility.Vector3dVector(
        np.asarray(colors, dtype=np.float64)
    )

    success = o3d.io.write_point_cloud(
        output_path,
        pcd
    )

    if not success:
        raise RuntimeError(
            f"Failed to save point cloud: {output_path}"
        )

    return output_path


# =========================================================
# ANALYTICS
# =========================================================

def build_analytics(
    sparse_points,
    dense_points,
    camera_positions,
    processing_time,
    total_input_images,
    registered_images
):

    total_points = (
        len(sparse_points)
        + len(dense_points)
    )

    registration_ratio = (
        len(registered_images)
        / max(total_input_images, 1)
    )

    # Temporary audit metric.
    # We will replace this with proper quality metrics
    # during the analytics stage.
    health_score = round(
        registration_ratio * 100.0,
        2
    )

    return {

        "total_sparse_points":
            int(len(sparse_points)),

        "total_dense_points":
            int(len(dense_points)),

        "total_points":
            int(total_points),

        "total_cameras":
            int(len(camera_positions)),

        "total_input_images":
            int(total_input_images),

        "registered_images":
            int(len(registered_images)),

        "registration_ratio":
            round(registration_ratio * 100.0, 2),

        "processing_time":
            round(processing_time, 2),

        # Temporary placeholders.
        # Stage 5 will replace these.
        "successful_pairs":
            0,

        "failed_pairs":
            0,

        "avg_confidence":
            0.0,

        "avg_inliers":
            0,

        "avg_points":
            int(total_points),

        "health_score":
            health_score
    }


# =========================================================
# MAIN
# =========================================================

def run_reconstruction(
    uploaded_files,
    dense_ply_path,
    progress_callback=print
):
    """
    Process the COLMAP reconstruction results.

    Objective
    ---------
    Consume the dense point cloud generated by COLMAP,
    clean it, generate a mesh, and produce analytics
    for the PowerTwinAI application.

    Parameters
    ----------
    uploaded_files : list[dict]
        Prepared image information produced by the
        preprocessing stage.

    dense_ply_path : str
        Path to COLMAP's fused dense point cloud.

    progress_callback : callable
        Logging callback used by the reconstruction runner.

    Returns
    -------
    tuple
        Final points, colors, camera positions,
        match visuals, PLY path, pair logs,
        processing time, and analytics.
    """

    start_time = time.time()

    progress_callback(
        "[RECONSTRUCTION] Processing COLMAP results..."
    )

    # =====================================================
    # INPUT VALIDATION
    # =====================================================

    if not dense_ply_path:

        raise ValueError(
            "COLMAP dense point-cloud path was not provided."
        )

    if not os.path.exists(dense_ply_path):

        raise FileNotFoundError(
            "COLMAP dense point cloud not found: "
            f"{dense_ply_path}"
        )

    # =====================================================
    # INPUT IMAGE COUNT
    # =====================================================

    total_input_images = len(
        uploaded_files
    )

    progress_callback(
        f"[RECONSTRUCTION] Input images: "
        f"{total_input_images}"
    )

    # =====================================================
    # LOAD COLMAP SPARSE MODEL
    # =====================================================

    progress_callback(
        "[COLMAP] Loading sparse reconstruction..."
    )

    (
        cameras,
        registered_images,
        _camera_positions,
        sparse_points,
        sparse_colors
    ) = load_colmap_model(
        "colmap_data"
    )

    progress_callback(
        f"[COLMAP] Registered Images: "
        f"{len(registered_images)}"
    )

    progress_callback(
        f"[COLMAP] Sparse Points: "
        f"{len(sparse_points)}"
    )

    # =====================================================
    # CAMERA POSITIONS
    # =====================================================

    camera_positions = []

    for image_name, pose in registered_images.items():

        camera_positions.append(
            pose["camera_center"]
        )

    camera_positions = np.asarray(
        camera_positions,
        dtype=np.float64
    )

    # =====================================================
    # LOAD COLMAP DENSE POINT CLOUD
    # =====================================================

    progress_callback(
        "[COLMAP-DENSE] Loading fused dense point cloud..."
    )

    dense_pcd = o3d.io.read_point_cloud(
        dense_ply_path
    )

    if dense_pcd.is_empty():

        raise RuntimeError(
            "COLMAP fused point cloud is empty."
        )

    dense_points = np.asarray(
        dense_pcd.points,
        dtype=np.float64
    )

    # =====================================================
    # DENSE COLORS
    # =====================================================

    if dense_pcd.has_colors():

        dense_colors = np.asarray(
            dense_pcd.colors,
            dtype=np.float64
        )

    else:

        progress_callback(
            "[WARNING] Dense point cloud has no colors."
        )

        dense_colors = np.ones(
            (len(dense_points), 3),
            dtype=np.float64
        )

    progress_callback(
        f"[COLMAP-DENSE] Dense Points: "
        f"{len(dense_points):,}"
    )

    # =====================================================
    # REMOVE INVALID VALUES
    # =====================================================

    finite_mask = (
        np.all(
            np.isfinite(dense_points),
            axis=1
        )
        &
        np.all(
            np.isfinite(dense_colors),
            axis=1
        )
    )

    dense_points = dense_points[
        finite_mask
    ]

    dense_colors = dense_colors[
        finite_mask
    ]

    if len(dense_points) == 0:

        raise RuntimeError(
            "All COLMAP dense points were invalid."
        )

    # Keep colors valid for Open3D.
    dense_colors = np.clip(
        dense_colors,
        0.0,
        1.0
    )

    # =====================================================
    # CLEAN DENSE POINT CLOUD
    # =====================================================

    progress_callback(
        "[CLEANING] Cleaning COLMAP dense point cloud..."
    )

    pcd = o3d.geometry.PointCloud()

    pcd.points = (
        o3d.utility.Vector3dVector(
            dense_points
        )
    )

    pcd.colors = (
        o3d.utility.Vector3dVector(
            dense_colors
        )
    )

    # =====================================================
    # STATISTICAL OUTLIER REMOVAL
    # =====================================================

    if len(dense_points) >= 50:

        try:

            pcd, _ = (
                pcd.remove_statistical_outlier(
                    nb_neighbors=20,
                    std_ratio=2.0
                )
            )

        except Exception as e:

            print(
                "[WARNING] Point-cloud cleaning "
                f"failed: {e}"
            )

    final_points = np.asarray(
        pcd.points,
        dtype=np.float64
    )

    final_colors = np.asarray(
        pcd.colors,
        dtype=np.float64
    )

    if len(final_points) == 0:

        raise RuntimeError(
            "Point-cloud cleaning removed all points."
        )

    progress_callback(
        f"[CLEANING] Final Points: "
        f"{len(final_points):,}"
    )

    # =====================================================
    # OUTPUT DIRECTORY
    # =====================================================

    os.makedirs(
        "output",
        exist_ok=True
    )

    # =====================================================
    # SAVE FINAL POINT CLOUD
    # =====================================================

    ply_path = save_point_cloud(
        final_points,
        final_colors,
        os.path.join(
            "output",
            "reconstruction.ply"
        )
    )

    progress_callback(
        f"[OUTPUT] Point Cloud Saved: "
        f"{ply_path}"
    )

    # =====================================================
    # MESH
    # =====================================================

    progress_callback(
        "[MESH] Generating Mesh..."
    )

    try:

        mesh_result = generate_mesh(
            final_points,
            final_colors,
            output_dir="output"
        )

        gc.collect()

        if mesh_result is not None:

            progress_callback(
                f"[MESH] Vertices: "
                f"{mesh_result['vertices']:,}"
            )

            progress_callback(
                f"[MESH] Triangles: "
                f"{mesh_result['triangles']:,}"
            )

    except Exception as e:

        print(
            f"[WARNING] Mesh generation failed: {e}"
        )

        mesh_result = None

    # =====================================================
    # PAIR LOGS
    # =====================================================

    pair_logs = []

    pair_log_path = os.path.join(
        "output",
        "pair_logs.csv"
    )

    with open(
        pair_log_path,
        "w",
        newline="",
        encoding="utf-8"
    ) as csv_file:

        writer = csv.writer(
            csv_file
        )

        writer.writerow([
            "pair",
            "status",
            "confidence",
            "inliers",
            "points"
        ])

    # =====================================================
    # ANALYTICS
    # =====================================================

    processing_time = (
        time.time() - start_time
    )

    analytics = build_analytics(
        sparse_points,
        final_points,
        camera_positions,
        processing_time,
        total_input_images,
        registered_images
    )

    # =====================================================
    # RESULT DATA
    # =====================================================

    match_visuals = []

    progress_callback(
        "[RECONSTRUCTION] COLMAP result processing complete."
    )

    progress_callback(
        f"[INFO] Final Points: "
        f"{len(final_points):,}"
    )

    progress_callback(
        f"[INFO] Registered Cameras: "
        f"{len(camera_positions)}"
    )

    progress_callback(
        f"[INFO] Processing Time: "
        f"{processing_time:.2f} sec"
    )

    return (
        final_points,
        final_colors,
        camera_positions,
        match_visuals,
        ply_path,
        pair_logs,
        processing_time,
        analytics
    )